### ISSUE TITLE
Can I use this to run inference on my custom data?

### ISSUE THREAD

**Issue by HenrySomeCode** [VinAIResearch/HyperCUT#1]
Say I have this blurred image A, I want to convert it into an image sequence. How can I do it?

Is that via this command? 

python test_blur2vid.py --dataset_name dataname \
			--metadata_root path/to/generated_metadata.json \
			--batch_size 8 \
			--backbone Jin \ 
			--hypercut_path path/to/pretrained_HyperCUT.pth \
			--target_frames 1 2 3 4 5 6 7 \	
Or this command? 

python generate_order.py --dataset_name dataname \
			--metadata_root path/to/metadata.json \
    			--save_path path/to/generated_metadata.json \
    			--pretrained_path path/to/pretrained_HyperCUT.pth \
    			
Also, I don't get the idea that I have to put a generated_metadata.json or metadata.json into the command everytime I want to run inference. The format of the json must contain sharp images while I can't have these images until I use HyperCUT model: 

{
    "name": "Street",
    "frame_per_seq": 7,
    "data": [
        {
            "id": "00000/0000",
            "order": "ignore",
            "partition": "train",
            "blur_path": "00000/blur/0000.png", #path_to_image
            "frame001_path": "00000/sharp/0000_1.png", 
            "frame002_path": "00000/sharp/0000_2.png",
            "frame003_path": "00000/sharp/0000_3.png",
            "frame004_path": "00000/sharp/0000_4.png",
            "frame005_path": "00000/sharp/0000_5.png",
            "frame006_path": "00000/sharp/0000_6.png",
            "frame007_path": "00000/sharp/0000_7.png"
        },
	{
			...
	}
    ]
}

**Comment by zero1778** [comment]
Thank you for your inquiry regarding the inference process. I'd like to clarify that the commands you mentioned are designed for evaluating the methods we've developed. To ensure an accurate evaluation, the presence of the **metadata.json** file is crucial, as it contains the necessary ground truth data for comparison.

It's important to note that our HyperCUT differs from the Blur2Vid model backbone. HyperCUT serves as a regularization scheme designed to enhance the generation of output. It achieves this by imposing constraints that promote the production of avoiding order-ambiguity issue, thus having high-quality results. For a comprehensive understanding of our baseline and the overall process, I recommend referring to our published paper. It provides in-depth insights into our methods and their implementation. 

Furthermore, we've recently updated the sample inference code to accommodate the Jin backbone. This code exemplifies the inference process employed in our proposal. Detailed instructions for running this code can be found in the repository's **README**.

Feel free to reach out if you have any more questions or require further assistance. We're here to help you with any inquiries you may have.
